### ISSUE TITLE
商品一覧を閲覧したい

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/shopping-cart#1]
- `list`コマンドで商品一覧を表示する
- `--オプション`で細かい検索条件の指定ができる
  - `--name 名前`で、曖昧一致検索
  - `--price 価格-価格`で、その価格内に収まる商品を検索
  - `--sort オプション`で検索結果の昇順ソート
    - `--sort name`で商品名ソート
    - `--sort price`で価格順ソート

初期の商品リストは以下の通り。

|商品名|商品説明|価格|在庫|
|-|-|-|-|
|消しゴム|モノけし|120|30|
|ノート|自由帳|200|100|
|椅子|座椅子|3000|20|
|ソファー|リクライニング機能付き|15000|5|
|机|四つ足の机|5000|5|
|携帯電話|SIMカード無|30000|10|
|充電器|タイプCの充電器|2000|10|
|ゴミ箱|そこは浅め|1500|20|
|掃除機|コードレス|23000|8|
|パソコン|ノートPC|22000|5|
|色鉛筆セット|12色の色鉛筆|900|20|
|鉛筆|六角形の鉛筆|100|50|
|applewatch|中古|11000|2|

**Comment by kitazawasyogo** [comment]
仕様についてご確認したいことがございます。

①入出力は何で行いますか？
例：コンソール
②商品一覧の表示方法はどのように表示しますか？
例：初期の商品リストの表のように画面に表示する。
③初めにコマンドやオプションの一覧などは表示しますか？
④想定外の入力があった場合の挙動はどうしますか？
⑤listコマンドが入力されるまでは画面に何も表示されていないかと思いますが、listコマンドの入力を求める文言などは画面に表示しますか？

以上、よろしくお願いいたします。

**Comment by nabemasamasa** [comment]
- ①: はい、例の通りコンソールアプリケーションでお願いします。
- ②: はい、イメージとしては提示した表のようにお願いしたいです。コンソールに出力する為、出力形式については指定があります。
   - 1行目に項目名を、2行目以降に商品ごとの内容でお願いします。
   - 半角スペースで横幅を整えてください。項目同士の間は半角スペース一個でお願いします。
- ③:  アプリケーションを起動した際に、コマンドやオプションの一覧は表示しなくて結構です。
- ④: 「入力内容が正しくありません。」を表示してください。
    - ただし、頭2文字が一致している場合はBashのように「もしかして: コマンド名」などサジェストを表示してほしいです。
- ⑤: ③でも回答した通り、起動時は何も表示しません。ですが、ショッピングカードアプリはBashで使用できるコマンドを参考にしている為、「--help」でヘルプ表示できるようにしてほしいです。
    - 「help」で使えるコマンドとその内容の一覧を表示してください
    - 「コマンド --help」の組み合わせでそのコマンドで使えるオプションとその内容の一覧を表示してください
    - このヘルプ機能は機能追加したタイミングで、あわせて追加してほしいです。

不明点などありましたら、お手数ですがご確認ください。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。
仕様に合わせて実装させていただきます。

見積もり出来ましたら、後ほどご連絡させていただきます。

**Comment by kitazawasyogo** [comment]
商品一覧を閲覧する機能追加の見積もり時間30hとさせてください。
(PR立てる所までです。)

**Comment by nabemasamasa** [comment]
30h見込み、了解です。
対応をお願いします。

**Comment by kitazawasyogo** [comment]
お疲れ様です。
30ｈ見積もりとお伝えしましたが、時間内に終える事が厳しい状態です。
申し訳ございません。

見積もり38ｈとさせてください。
（15日（水）11時30迄）

**Comment by nabemasamasa** [comment]
あと8hくらいで終わる見込み、了解しました。
間に合わなそうだとわかったら、わかった時点で連絡お願いします。

-----以下、開発者としてのコメント。-----
見積もり報告から計算して大体3/14お昼過ぎくらいにPR立つイメージだったので、(タイミングはともかく)事前連絡自体は 👍 です。(期日過ぎて突っつかれてごめんなさいするよりは遥かに良い)
今回からの見積もり練習ということで、練習なので極論いくらでも失敗してもいいですが、
本番だと直前にごめんなさいすると、例えば保守の不具合修正だと作業をお願いしているお客様も困ります(業務止めてたら猶更。○○日に復旧しますとかユーザーに展開してるかも知れないし…さらに他の会社まで巻き込むような業務が止まってたら信用問題にまで…)
開発案件とかでも、PMの人が期日までに間に合うかどうかなどリスケしたりやタスクの再分配などする時間がカツカツになっちゃいます。
早め早めに、報告・連絡・相談しましょう。
それはそれとして、PR立てたら今回見積もりしてみてどうだったか、振り返りましょう。)

**Comment by kitazawasyogo** [comment]
お疲れ様です。

昨日の時点でお伝えした見積もりの時間内に終えられず、38ｈに変更させていただきましたが38ｈの時間内に収める事が厳しい状態です。
申し訳ございません。

見積もり46ｈとさせてください。
（16日（木）PM１時）

**Comment by nabemasamasa** [comment]
3/16(木) の13:00頃、了解しました。

**Comment by kitazawasyogo** [comment]
お疲れ様です。

昨日の時点でお伝えした見積もりの時間内に終えられず、時間内に収める事が厳しい状態です。
度重なる変更、直前の報告となってしまい申し訳ございません。

見積もり48ｈとさせてください。
（16日（木）PM3時）

**Comment by nabemasamasa** [comment]
了解です、引き続きお願いします。

**Comment by kitazawasyogo** [comment]
お疲れ様です。

先程お伝えした見積もりの時間内に終えられず、時間内に収める事が厳しい状態です。
度重なる変更、直前の報告となってしまい申し訳ございません。

見積もり51ｈとさせてください。
（17日（金）AM9時）

（Push出来るコミットの状態でない為コミットを分けなおす作業時間頂きたいです。）

**Comment by kitazawasyogo** [comment]
お疲れ様です。

仕様について確認したいことがございます。

①価格検索オプションの入力した価格の範囲の値が想定外だった場合の挙動について
以下の例のケースと挙動が考えられますが仕様について指定はございますか？

例：list --prrrrrr 100-200　頭2文字は一致しているが想定外の入力値の場合
　→「入力内容が正しくありません。もしかして：list --price 価格-価格」メッセージとサジェスト表示し再入力を求める。
例：list --price 10-20   検索結果0件の場合
        　  →商品リストの項目のみ表示する。
例：list --price 200000-20
　　list --price 三千円
　　list --price 100-200-300　 価格の入力値が正しくない場合
        　 →「入力内容が正しくありません。」のメッセージを表示し再入力を求める。

②提示して頂いた初期の商品リストについての疑問点について
　１．商品名：消しゴム　の商品説明：モノけし　とはどのようなものでしょうか？
　２．商品名：ゴミ箱　の商品説明：そこは浅め　の「そこ」はゴミ箱の底を指しているかと思いますが、ひらがなである　　　　　　　　　理由はございますか？　　
　３．商品名：applewatch　は全て小文字である理由はございますか？

**Comment by nabemasamasa** [comment]
①については、提示いただいた例と動作のようにお願いします。
②-1:トンボ鉛筆の「MONO」が書かれた消しゴムの事です。
②-2:指摘ありがとうございます。「底は浅め」の意図なので、ひらがなである事に理由はないです。仕様提示の際に変換されなかったものと思います。
③-3:特に理由はありません。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。

①につていは例のような挙動にいたします。
②-2「そこは浅め」の文言は「底は浅め」に変更いたします。
